### ISSUE TITLE
Testing with Canvas issue

### ISSUE THREAD

**Issue by pushyamig** [dmitry-viskov/pylti1.3-django-example#3]
I am trying to test out the` pylti1.3-django-example` repo with our Canvas test instance, the LTI launch seems to be successful. 
The problem I am facing is when trying to make api call with `scoreboard` for getting assignment grades I am seeing a 401
 `{"status":"unauthenticated","errors":[{"message":"user authorization required"}]}`. 
`https://bff61e2a5520.ngrok.io/api/scoreboard/lti1p3-launch-507-478c-a893-649c5d665d12/`
and the log reflects this 

```
Traceback (most recent call last):
File "/usr/local/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
   File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
     response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/game/game/views.py", line 208, in scoreboard
   scores = ags.get_grades(score_line_item)
   File "/usr/local/lib/python3.6/site-packages/pylti1p3/assignments_grades.py", line 99, in get_grades
     line_item = self.find_or_create_lineitem(line_item, find_by=find_by)
   File "/usr/local/lib/python3.6/site-packages/pylti1p3/assignments_grades.py", line 70, in find_or_create_lineitem
    line_item = self.find_lineitem_by_tag(new_line_item.get_tag())
  File "/usr/local/lib/python3.6/site-packages/pylti1p3/assignments_grades.py", line 60, in find_lineitem_by_tag
     line_items = self.get_lineitems()
  File "/usr/local/lib/python3.6/site-packages/pylti1p3/assignments_grades.py", line 46, in get_lineitems
   accept='application/vnd.ims.lis.v2.lineitemcontainer+json'
  File "/usr/local/lib/python3.6/site-packages/pylti1p3/service_connector.py", line 86, in make_service_request
   raise LtiException('HTTP response [%s]: %s - %s' % (url, str(r.status_code), r.text))
 pylti1p3.exception.LtiException: HTTP response [https://something.test.instructure.com/api/lti/courses/2324424/line_items]: 401 - {"status":"unauthenticated","errors":[{"message":"user authorization required"}]}
```

LTI Launch works and Deep links work as well. I just git cloned this repo and tried it so all the pip version are as required.
![Screen Shot 2020-06-18 at 4 17 02 PM](https://user-images.githubusercontent.com/8579775/85068259-16858200-b180-11ea-83e2-a460d0f11085.png)
Can you suggest what's going on?

**Comment by dmitry-viskov** [comment]
hi @pushyamig .

I may assume that you have no permissions to access assignment data on the canvas side.
Please check that you enabled all LTI Advantage services in the Developer Key settings:

<img width="1573" alt="Screenshot 2020-06-19 в 12 19 33" src="https://user-images.githubusercontent.com/1876893/85117203-2c01b700-b227-11ea-98b3-e18b503a14cb.png">

**Comment by pushyamig** [comment]
Hi @dmitry-viskov , Thanks for the response.
Here are the settings from my LTI KEY. I turned on everything.
<img width="827" alt="Screen Shot 2020-06-19 at 7 04 00 AM" src="https://user-images.githubusercontent.com/8579775/85126325-41f98280-b1fb-11ea-9f7a-0ac6fbddee47.png">

I tried to create my own public/private and used what you have provided. but still no effect. I have canvas admin privileges. In the course, I tried to be both students and teacher roles. Still I see the error 401

**Comment by dmitry-viskov** [comment]
@pushyamig Unfortunately don't know the reason of such behaviour. Something wrong in you local settings or may be in your canvas instance. The error looks like you don't have permissions to access AGS service. My local canvas instance working well:

<img width="1627" alt="Screenshot 2020-06-19 в 12 23 20" src="https://user-images.githubusercontent.com/1876893/85187638-93f8e180-b2a9-11ea-9cd6-2386b43339d7.png">

**Comment by pushyamig** [comment]
Ok, I don’t think my local setup has an issue. I verified twice. I will try to follow up with canvas if something in the test env configuration causing any issue. Thanks for the examples you added for demonstrating the LTI1.3 it is very helpful!

**Comment by pushyamig** [comment]
@dmitry-viskov indeed it was a configuration issue in our Canvas test/beta instance. By Default AGS and NRPS are disabled in non prod if your institution is not allowing access to students in non prod canvas env. This post was useful in solving the error https://community.canvaslms.com/t5/Developers-Group/401-Error-with-LTI-1-3-Service-Tokens/m-p/190046#M5242.
