### ISSUE TITLE
Missing "target_link_uri" param

### ISSUE THREAD

**Issue by ashutoshsoni891** [dmitry-viskov/pylti1.3-django-example#4]
Hi there!
First of all , Thanks for making python package of LTI.I am trying to hit [localhost:9001/login](localhost url) but it says : 

**Missing "target_link_uri" param**
--
There is no suck key exists in game.json , however I have target_link_uri : [see this](https://lti-ri.imsglobal.org/lti/tools/1364/deep_link_launches). I am running `docker-compose up --build` .Also after successfully running this repo , will we be certified ? because I already successfully published testing tool here : `(https://lti-ri.imsglobal.org/platforms/1366)`
Could you please help me out ?

**Comment by ashutoshsoni891** [comment]
> Hi there!
> First of all , Thanks for making python package of LTI.I am trying to hit [localhost:9001/login](localhost url) but it says :
> 
> ## **Missing "target_link_uri" param**
> There is no suck key exists in game.json , however I have target_link_uri : [see this](https://lti-ri.imsglobal.org/lti/tools/1364/deep_link_launches).
> Could you please help me out ?

**Comment by dmitry-viskov** [comment]
hi @ashutoshsoni891 

>Missing "target_link_uri" param

means that external platform did not pass `target_link_uri` POST/GET parameter during login step
